Made some adjustments to nekvariables - the adapted scripts are close to working on Blue Waters now. PGI is just complaining about some line endings or something.

diff --git a/nekvariables/tools/maketools b/nekvariables/tools/maketools
--- a/nekvariables/tools/maketools
+++ b/nekvariables/tools/maketools
@@ -1,24 +1,110 @@
 #!/bin/bash
 
-### edit config, not this!!! ###############################
+# binary path
+mkdir -p $HOME/bin
+bin_nek_tools="$HOME/bin"
+
+# specify your compilers here
+F77="gfortran"
+CC="gcc"
+
+# enable BIG MEMORY suuport
+BIGMEM="true"
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+### don't touch this section ###############################
 
 if [ $# -eq 0 ]; then
    echo "Usage: maketools [clean|all|tool(s)]"
    exit 1
 fi
 
-source scripts/nekvariables/R8_BIGMEM
+if [ "$F77" == "" ]; then
+  echo "FATAL ERROR: Specify your Fortran compiler in maketools!"
+  exit 1
+fi
+
+if [ "$CC" == "" ]; then
+  echo "FATAL ERROR: Specify your C compiler in maketools!"
+  exit 1
+fi
 
 # overwrite source path with optional 2nd argument
 if [ $# -eq 2 ]; then
-  echo "Overwriting source path with: $2"
   bin_nek_tools="$2"
+fi
+
+
+
+
+which `echo $F77 | awk '{print $1}'` 1>/dev/null
+if [ $? -ne 0 ]; then
+  echo "FATAL ERROR: Cannot find $F77!"
+  exit 1
+fi
+
+which `echo $CC | awk '{print $1}'` 1>/dev/null
+if [ $? -ne 0 ]; then
+  echo "FATAL ERROR: Cannot find $CC!"
+  exit 1
 fi
 
 if [ ! -d $bin_nek_tools  ]; then
   echo "FATAL ERROR: install path $bin_nek_tools does not exist!"
   exit 1
 fi
+
+
+case $F77 in
+  *pgf*)       R8="-r8"
+               BIGMEM_FLAG="-mcmodel=medium"
+               ;;
+  *gfortran*)  R8="-fdefault-real-8"
+               BIGMEM_FLAG="-mcmodel=medium"
+               ;;
+  *ifort*)     R8="-r8"
+               BIGMEM_FLAG="-mcmodel=medium -shared-intel"
+               ;;
+  *pathf*)     R8="-r8"
+               ;;
+  *xlf*)       R8="-qrealsize=8"
+               BIGMEM_FLAG="-q64"
+               ;;
+  *ftn*)       R8="-r8"
+               BIGMEM_FLAG="-mcmodel=medium"
+               ;;
+  *)           echo "Error: Unable to detect compiler!"
+               exit 1
+               ;;
+esac
 
 # Check if the compiler adds an underscore to external functions
 cat > test_underscore.f << _ACEOF
@@ -34,6 +120,14 @@ if [ $? -eq 0 ]; then
 fi
 \rm test_underscore.* 2>/dev/null
 
+
+F77="$F77" 
+CC="$CC" 
+if [ "$BIGMEM" == "true" ] || [ "$BIGMEM" == "TRUE" ]; then
+  F77="$F77 $BIGMEM_FLAG" 
+  CC="$CC $BIGMEM_FLAG" 
+fi
+
 export F77
 export CC
 export bin_nek_tools
@@ -45,13 +139,12 @@ MODULES=`echo $LIST`
 export MODULES
 
 if [ "$1" == "clean" ]; then
-  make clean
+   make clean
 else
-  if [ "$1" != "all" ]; then
-     LIST=`echo $* | sed 's:\/::g'`
-     MODULES=$LIST
-  fi
-  export MODULES
-  make 
+   if [ "$1" != "all" ]; then
+      LIST=`echo $* | sed 's:\/::g'`
+      MODULES=$LIST
+   fi
+   export MODULES
+   make 
 fi
-
